version: '3'
services:
    nginx:
        ports:
            - "8081:80"
        image: nginx
        volumes:
            - "./dist/public:/usr/share/nginx/html:ro"
            - "./others/default.conf:/etc/nginx/conf.d/default.conf"
        environment:
            - TZ=Asia/Taipei
    mongo:
        ports:
            - "27017:27017"
        volumes:
            - "/home/jjj/mongoData:/data/db"
        environment:
            - TZ=Asia/Taipei
        image: mongo
        command: [--auth]
