service: express-ahorro
useDotenv: true
custom:
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true
plugins:
  - serverless-webpack
  - serverless-offline
provider:
  name: aws
  runtime: nodejs14.x
  region: ap-southeast-1
  apiGateway:
    minimumCompressionSize: 1024
    shouldStartNameWithService: true
  environment:
    AWS_NODEJS_CONNECTION_REUSE_ENABLED: 1
    SERVER_PORT: 3333
    MONGO_USER: ${ssm:/lambda/ahorro/prod/MONGO_USER}
    MONGO_PASSWORD: ${ssm:/lambda/ahorro/prod/MONGO_PASSWORD}
    MONGO_PATH: ${ssm:/lambda/ahorro/prod/MONGO_PATH}
    HOST_URL: https://ahorrojs.netlify.app
    JWT_ACCESS_TOKEN_SECRET: ${ssm:/lambda/ahorro/prod/JWT_ACCESS_TOKEN_SECRET}
    JWT_ACCESS_TOKEN_EXPIRATION_TIME: 900
    JWT_REFRESH_TOKEN_SECRET: ${ssm:/lambda/ahorro/prod/JWT_REFRESH_TOKEN_SECRET}
    JWT_REFRESH_TOKEN_EXPIRATION_TIME: 36000
    COOKIE_SECRET: ${ssm:/lambda/ahorro/prod/COOKIE_SECRET}
    GOOGLE_CLIENT_ID: ${ssm:/lambda/ahorro/prod/GOOGLE_CLIENT_ID}
    GOOGLE_CLIENT_SECRET: ${ssm:/lambda/ahorro/prod/GOOGLE_CLIENT_SECRET}
    FB_CLIENT_ID: ${ssm:/lambda/ahorro/prod/FB_CLIENT_ID}
    FB_CLIENT_SECRET: ${ssm:/lambda/ahorro/prod/FB_CLIENT_SECRET}
    VUE_APP_BACKEND_API_BASE_URL: ${env:VUE_APP_BACKEND_API_BASE_URL}
package:
  individually: true
functions:
  express:
    handler: dist/server.handler
    events:
      - http:
          method: ANY
          path: /
      - http:
          method: GET
          path: /entries
      - http:
          method: POST
          path: /entries/sync
      - http:
          method: GET
          path: /entries/sync/callback
      - http:
          method: GET
          path: /entries/monthly
      - http:
          method: POST
          path: /auth/login/{type}
      - http:
          method: POST
          path: /auth/login
      - http:
          method: GET
          path: /auth/callback/{type}
      - http:
          method: POST
          path: /auth/refresh
      - http:
          method: POST
          path: /auth/logout