version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:14.16.1
      - image: circleci/mongo:4.4.6
    steps:
      - run:
          name: MongoDB Install
          command: |
             sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 9DA31620334BD75D9DCB49F368818C72E52529D4
             echo "deb [ arch=amd64 ] https://repo.mongodb.org/apt/ubuntu bionic/mongodb-org/4.0 multiverse" | sudo tee /etc/apt/sources.list.d/mongodb-org-4.0.list
             sudo apt-get update
             sudo apt-get install -y mongodb-org-shell
      - setup_remote_docker
      - run:
          name: Waiting for Mongo
          command: dockerize -wait tcp://localhost:27017 -timeout 1m
      - checkout
      - run:
          name: Npm install
          command: npm ci
      - run:
          name: Set Up MongoDB
          command: |
            mongo --eval 'db.createUser({ user: "jjj", pwd: "1234", roles: [ { role: "readWrite", db: "test" } ] })'
      - run:
          name: Test
          command: ./node_modules/.bin/jest --config test/jest-e2e.json
