version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:14.16.1
      - image: circleci/mongo:4.4
        environment:
          MONGO_USERNAME: jjj
          MONGO_PASSWORD: 1234
    steps:
      - run:
          name: MongoDB Install
          command: |
             sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 9DA31620334BD75D9DCB49F368818C72E52529D4
             echo "deb [ arch=amd64 ] https://repo.mongodb.org/apt/ubuntu bionic/mongodb-org/4.0 multiverse" | sudo tee /etc/apt/sources.list.d/mongodb-org-4.0.list
             sudo apt-get update
             sudo apt-get install -y mongodb-org-shell
      - setup_remote_docker
      - run:
          name: Waiting for Mongo
          command: dockerize -wait tcp://localhost:27017 -timeout 1m
      - checkout
      - run:
          name: Npm install
          command: npm install
      - run:
          name: Get versions
          command: |
              node -v
              npm -v
              mongo --version
              mongo localhost --eval "db.version()"
      - run:
          name: Test
          command: jest --config test/jest-e2e.json
              